
# Build Stage

FROM maven:3.9.10-amazoncorretto-17 AS build
WORKDIR ./build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime Stage
FROM amazoncorretto:17
ARG PROFILE=dev
ARG APP_VERSION=1.0.0
WORKDIR /app
COPY --from=build /build/target/movie-ticket-booking-*.jar /app/

EXPOSE 9099

ENV DB_URL=jdbc:postgresql://ticket_booking_pg_sql:5432/movie_ticket_booking
ENV ACTIVE_PROFILE=${PROFILE}
ENV JAR_VERSION=${APP_VERSION}

CMD java -jar -Dspring.profile.active=${ACTIVE_PROFILE} -Dspring.datasource.url=${DB_URL} movie-ticket-booking-${JAR_VERSION}.jar