

services:
  postgres:
    container_name: ticket_booking_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: tareq23
      POSTGRES_PASSWORD: tareq23
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: movie_ticket_booking
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ticket-booking-net
    restart: unless-stopped

  pgadmin:
    container_name: ticket_booking_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - ticket-booking-net
    restart: unless-stopped


  keycloak:
    container_name: ticket_booking_security_keycloak
    image: quay.io/keycloak/keycloak:26.2.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - 8090:8080
    command:
      - start-dev
    networks:
      - ticket-booking-net

  mtb:
    container_name: mtb_api
    image: mtb/mtb:1.0.0
    ports:
      - 9009:9099
    depends_on:
      - postgres
    networks:
      - ticket-booking-net

networks:
  ticket-booking-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:






