




spring:
  application:
    name: Movie Ticket Booking System

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_ticket_booking
    username: tareq23
    password: tareq23
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 9099







